sudo: required
services:
  - docker

before_install:
  - docker build -t swapnil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swapnil/docker-react npm run test -- --coverage

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "swap-docker-react"
  env: "SwapDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-821487860376"
  bucket-path: "swap-docker-react"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  